main:
  - name: "ChatGPT代升级服务"
    url: "/services/"
    weight: 10

  - name: "ChatGPT 使用指南"
    url: "/guides/"
    weight: 20

  - name: "ChatGPT-4o生图API，免费测试"
    url: "/api-free/"
    weight: 30
